
export const messages={
    en:{
        message:{
            app_title:'Iraq pilgrims',
            locations:'Locations',
            shrines:'Shrines',
            hotels:'Hotels',
            toilets:'Toilets',
            transportation:'Transportation',
            giftsVow:'Gifts And Vow  ',
            freeBooksCenters:'Free Boks Centers',
            restaurants:'Restaurants',
            hospitality:'Hospitality',
            visitorCities:'Visitor Cities',
            shrinesManagement:'Shrines Management',
            cityEntries:'City Entries',
            medicalCenters:'Medical Centers',
            map:'Map',
            emergency_lines:'Emergency Lines',
            emergency_line:'Emergency Line',
            religious_questions:'Religious Questions',
            books:'Books',
            location:'Location',
            answer_religious_questions:'Answer Religious Questions',
            //Books
            imam_sajad:'Imam Sajad',
            invocations_and_ziarat:'Invocations And Ziarat',
            islamic_ideology:'Islamic Ideology',
            science_of_imam_and_rise_of_martyrs_master:'Science Of Imam And Rise Of Martyrs Master',
            science_of_imam_scientist_tabatabai:'Science Of Imam By Scientist Tabatabai',
            shia_in_islam:'Shia  In Islam',
            who_is_hussein:'Who Is Hussein',
            who_is_sajad:'Who Is Sajad',
            ziarat:'Ziarat',
            //Language
            english:'English',
            france:'France',
            germany:'Germany',
            russia:'Russia',
            ardo_persian:'Ardo And Persian',
            ardo:'Ardo',
            kajaratia:'Kajaratia',
            
        }
    },
    fr:{
        message:{
            app_title:'Pèlerins en Irak',
            locations:'Emplacements',
            shrines:'sanctuaires',
            hotels:'hôtels',
            toilets:'toilettes',
            transportation:'transport',
            giftsVow:'cadeaux et vœux',
            freeBooksCenters:'librairies gratuites',
            restaurants:'restaurants',
            hospitality:'hospitalité',
            visitorCities:'Villes visiteurs',
            shrinesManagement:'Gestion des sanctuaires',
            cityEntries:'Les entrées de la ville',
            medicalCenters:'Centres médicaux',
            map:'Carte',
            emergency_lines:'Lignes durgence',
            emergency_line:'Ligne durgence',
            religious_questions:'Questions religieuses',
            books:'Livres',
            location:'Emplacement',
            answer_religious_questions:'Répondez aux questions religieuses',
            //Books
            imam_sajad:'Imam Sajad',
            invocations_and_ziarat:'Invocations And Ziarat',
            islamic_ideology:'Islamic Ideology',
            science_of_imam_and_rise_of_martyrs_master:'Science Of Imam And Rise Of Martyrs Master',
            science_of_imam_scientist_tabatabai:'Science Of Imam By Scientist Tabatabai',
            shia_in_islam:'Shia  In Islam',
            who_is_hussein:'Who Is Hussein',
            who_is_sajad:'Who Is Sajad',
            ziarat:'Ziarat',
            //Language
            english:'English',
            france:'France',
            germany:'Germany',
            russia:'Russia',
            ardo_persian:'Ardo And Persian',
            ardo:'Ardo',
            kajaratia:'Kajaratia',
        }
    },
    fa:{
        message:{
            app_title:'خدمات مهمان',
            locations:'مکان ها',
            shrines:'زیارتگاه ها',
            hotels:'هتل ها',
            toilets:'توالت',
            transportation:'حمل و نقل',
            giftsVow:'هدایا و وفات',
            freeBooksCenters:'مراکز کتاب رایگان',
            restaurants:'رستوران ها',
            hospitality:'مهمان نوازی',
            visitorCities:'شهرهای بازدید کننده',
            shrinesManagement:'مدیریت حرم',
            cityEntries:'مطالب شهر',
            medicalCenters:'مراکز پزشکی',
            map:'نقشه',
            emergency_lines:'خطوط اضطراری',
            emergency_line:'خط اضطراری',
            religious_questions:'سوالات دینی',
            books:'کتاب ها',
            location:'محل',
            answer_religious_questions:'جواب سوالات مذهبی',
            //Books
            imam_sajad:'Imam Sajad',
            invocations_and_ziarat:'Invocations And Ziarat',
            islamic_ideology:'Islamic Ideology',
            science_of_imam_and_rise_of_martyrs_master:'Science Of Imam And Rise Of Martyrs Master',
            science_of_imam_scientist_tabatabai:'Science Of Imam By Scientist Tabatabai',
            shia_in_islam:'Shia  In Islam',
            who_is_hussein:'Who Is Hussein',
            who_is_sajad:'Who Is Sajad',
            ziarat:'Ziarat',
            //Language
            english:'انگلیسی',
            france:'فرانسه',
            germany:'آلمان',
            russia:'روسیه',
            ardo_persian:'فارسی و آرود',
            ardo:'آرو',
            kajaratia:'جاكا',
        }
    },
    
}